title: K8sReady
description: Infraestructura Cloud moderna, segura y eficiente
baseurl: ""
url: "https://pierinho13.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Permalinks
permalink: pretty

